-- CRIAR UM BANCO DE DADOS:
CREATE DATABASE DATABASE_TEST_2

-- DELETAR UM BANCO DE DADOS:
DROP DATABASE DATABASE_TEST_2

-- SERVIDOR DO CURSO:
-- .\SQLEXPRESS

-- RESTAURAR UM BANCO DE DADOS:
-- Botão direito DATABASE 
	--> RESTORE DATABASE 
	--> DEVICE
	--> ... --> ADD
	--> OK --> OK --> OK